const $ = s => document.querySelector(s);
const roleNames={manager:'管理版',operator:'企業版',viewer:'會議閱覽',observer:'受限觀察者',support:'SaaS 服務後台'};
let identity, current='analytics';
const labels={analytics:'會議分析',meetings:'內容與授權',health:'服務狀態',audit:'存取稽核'};
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
const button=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=()=>Promise.resolve().then(fn).catch(error);return b};
function error(e){$('#status').textContent=e.message;}
async function api(path,body,method){const r=await fetch('/api/'+path,{method:method||(body?'POST':'GET'),headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok){if(r.status===401){$('#workspace').hidden=true;$('#login').hidden=false;$('#logout').hidden=true;$('#panel').replaceChildren();identity=null;}throw Error(r.status===403?'此角色沒有存取權限。':data.error||'請求失敗');}return data;}
$('#login-form').onsubmit=async e=>{e.preventDefault();const token=$('#token').value;$('#token').value='';try{await api('login',{token});await start();}catch(e){error(e)}};
$('#logout').onclick=async()=>{await api('logout',{});location.reload()};
$('#refresh').onclick=()=>render().catch(error);
async function start(){identity=await api('me');$('#login').hidden=true;$('#workspace').hidden=false;$('#logout').hidden=false;$('#context').textContent=identity.tenant+' / '+roleNames[identity.role];const tabs=identity.role==='operator'?['analytics','meetings','health','audit']:identity.role==='support'?['health']:identity.role==='viewer'?['meetings']:['analytics'];current=tabs[0];$('#nav').replaceChildren(...tabs.map(t=>button(labels[t],()=>{current=t;return render()})));await render();}
function table(headers,rows){const wrap=el('div',undefined,'table-wrap'),t=el('table'),head=el('tr');headers.forEach(x=>head.append(el('th',x)));const thead=el('thead');thead.append(head);t.append(thead);const body=el('tbody');rows.forEach(row=>{const tr=el('tr');row.forEach(x=>{const td=el('td');td.append(x instanceof Node?x:el('span',String(x)));tr.append(td)});body.append(tr)});t.append(body);wrap.append(t);return wrap;}
async function render(){const pane=$('#panel');pane.replaceChildren();$('#status').textContent='';$('#title').textContent=labels[current];[...$('#nav').children].forEach(b=>b.classList.toggle('active',b.textContent===labels[current]));$('#description').textContent=current==='analytics'?'比較會議時長與主席介入，這裡不載入姓名或逐字稿。':current==='health'?'只呈現服務代碼與最近回報狀態，不包含客戶會議內容。':current==='audit'?'追蹤存取與授權結果；紀錄不含逐字稿。':'逐場授權。受限會議須由管理員配置內容許可。';
if(current==='health'){const data=await api('health');const names={chair:'主席判斷',discord:'Discord 連線',stt:'即時轉錄',tts:'主席語音'}, states={unknown:'尚無有效回報',ok:'正常',degraded:'效能下降',unavailable:'無法使用'};for(const c of data.components){const row=el('div',undefined,'row');const title=el('div');title.append(el('h2',names[c.component]),el('p',c.updated_at?new Date(c.updated_at*1000).toLocaleString():'等待服務監測回報','small'));row.append(title,el('strong',states[c.state]));pane.append(row)}return;}
if(current==='audit'){const data=await api('audit');pane.append(table(['時間','操作身分指紋','動作','結果'],data.entries.map(x=>[new Date(x.at*1000).toLocaleString(),x.actor,x.action,x.outcome])));return;}
const data=await api('analytics');const stats=el('div',undefined,'stats');for(const [v,l]of [[data.count,'場會議'],[data.total_minutes,'累計分鐘'],[data.meetings.reduce((s,m)=>s+m.interventions,0),'主席介入']]){const n=el('div',undefined,'stat');n.append(el('strong',v),el('span',l));stats.append(n)}pane.append(stats);
if(current==='meetings'&&identity.role==='operator'){const form=el('form',undefined,'import');const file=el('input');file.type='file';file.accept='.jsonl';file.required=true;file.setAttribute('aria-label','Ahem 事件檔');const policy=el('select');policy.setAttribute('aria-label','會議政策');for(const [v,l]of [['team','一般團隊'],['regulated','受限內容']]){const o=el('option',l);o.value=v;policy.append(o)}const days=el('input');days.type='number';days.min=1;days.max=30;days.value=7;days.setAttribute('aria-label','保存天數');const submit=el('button','匯入事件檔');form.append(file,policy,days,submit);form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;try{if(file.files[0].size>4000000)throw Error('事件檔超過 4 MB');const events=(await file.files[0].text()).trim().split('\n').map(JSON.parse);await api('meetings',{events,policy:policy.value,days:Number(days.value)});await render()}catch(e){error(e);submit.disabled=false}};pane.append(form);}
if(!data.meetings.length){pane.append(el('p','目前沒有可查看的會議。請先匯入事件或取得會議授權。','empty'));return;}
pane.append(table(['會議代碼','政策','分鐘','參與人數','發言段數','主席介入',...(current==='meetings'?['操作']:[])],data.meetings.map(m=>{const row=[m.id.slice(0,8),m.policy==='regulated'?'受限內容':'團隊',(m.duration_seconds/60).toFixed(1),m.participants,m.utterances,m.interventions];if(current==='meetings'){const actions=el('div',undefined,'actions');actions.append(button('查看內容',()=>detail(m)));if(identity.role==='operator'){actions.append(button('管理授權',()=>grants(m)),button('刪除',async()=>{if(confirm('永久刪除此場會議的儲存內容與授權？')){await api('meetings/'+m.id,null,'DELETE');await render()}}))}row.push(actions)}return row})));}
function detailPane(title){document.querySelector('.detail')?.remove();const pane=el('section',undefined,'detail');pane.append(el('h2',title));$('#panel').append(pane);return pane;}
async function detail(m){const pane=detailPane('內容存取用途');const purpose=el('select');purpose.setAttribute('aria-label','內容存取用途');for(const [v,l]of [['meeting_review','會議回顧'],['incident_review','事件調查']]){const o=el('option',l);o.value=v;purpose.append(o)}pane.append(purpose,button('確認讀取',async()=>{const data=await api('meetings/'+m.id+'/content',{purpose:purpose.value});pane.replaceChildren(el('h2','會議內容'));const list=el('div',undefined,'transcript');for(const e of data.events){if(e.kind==='meeting')pane.append(el('h3',e.data.topic||'會議'));if(e.kind==='utterance'||e.kind==='spoken')list.append(el('p',(e.data.speaker||'主席')+'：'+(e.data.text||'')))}pane.append(list);if(!list.children.length)pane.append(el('p','這份事件檔沒有逐字稿。'))}));}
async function grants(m){const data=await api('meetings/'+m.id+'/grants');const pane=detailPane('會議閱覽授權');if(!data.viewers.length)pane.append(el('p','此組織尚未配置閱覽帳號。'));for(const a of data.viewers){const row=el('div',undefined,'row');row.append(el('span',a.id),button(a.granted?'撤銷閱覽':'允許閱覽',async()=>{await api('meetings/'+m.id+'/grants',{actor:a.id,allow:!a.granted});await grants(m)}));pane.append(row)}}
start().catch(()=>{});
